<?php
declare(strict_types=1);
/** @var HighlightExtension $this */
?>
<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="highlight_enabled">
				<input type="checkbox" id="highlight_enabled" name="highlight_enabled" <?= $this->isHighlightEnabled() ? 'checked="checked"' : '' ?> />
				<?= _t('ext.highlight.enabled') ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="highlight_color"><?= _t('ext.highlight.color') ?></label>
		<div class="group-controls">
			<input type="color" id="highlight_color" name="highlight_color" value="<?= htmlspecialchars($this->getHighlightColor(), ENT_QUOTES, 'UTF-8') ?>" />
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>
</form>
